### ISSUE TITLE
Dark mode coloration of command bar

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#161]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue corrects a few issues with the command UI for the keyboards in dark mode:

1. The Scribe key icon should be white instead of black as shown below

![Screenshot_20240930_182219](https://github.com/user-attachments/assets/d3bd9cd2-4425-43e8-b501-852d7af94261)

2. The `X` to cancel the command selection or a command should also be white instead of black as is shown below
3. The color of the command keys should match the Scribe key and both should be dark Scribe blue (now the command keys are a bit lighter as shown below)

![Screenshot_20240930_182148](https://github.com/user-attachments/assets/c73d701a-c47c-46b3-821a-b40c4beb378a)

4. The command bar should be the same color as the rather than white as shown below
    - The color should be `2E2E2E`, the same color as the special keyboard keys in dark mode like delete, shift, etc

![Screenshot_20240930_182205](https://github.com/user-attachments/assets/493c63a7-5faf-4c37-9694-308697d767d9)

### Contribution

Lots to do in this issue, and totally fine to do more than one PR for the various changes! 🎃 Happy to support as needed and review PRs as they come 😊

**Comment by indra057** [comment]
hello sir can u please assign me this issue so i can get started .. and  if i need any help can i message here?

**Comment by andrewtavis** [comment]
Sure thing, @indra057! Please let us know if you need any assistance and we'll do our best to help 😊

**Comment by indra057** [comment]
sir i didnt find the code exactly where do i need to fix the issue can u please guide me..or give me some more hints...

**Comment by indra057** [comment]
@andrewtavis sir please reply

**Comment by andrewtavis** [comment]
Hi sorry, @indra057. A lot has come up recently between work and another program starting. @angrezichatterbox, would you be able to support here and direct @indra057 to where the change would need to happen for the command bar coloration?

**Comment by indra057** [comment]
sorry @andrewtavis sir i am new to android development and i can't support that much as i didn't even understand the codebase and what is exactly happening i am just looking for simple issues that i can fix 


where  should i change the commands exactly so that i can fix the issue of the coloration of the toolbar

**Comment by andrewtavis** [comment]
@angrezichatterbox will provide some guidance here today or tomorrow, @indra057 :) Again sorry that I can't look for you right now.

**Comment by angrezichatterbox** [comment]
@indra057, don’t worry if you’re new to Android development! I’ll give you a basic overview of how our codebase is structured, specifically regarding the keyboard functionality that you will be dealing with in this issue.

Currently, we’re focusing on three main files:

- Services Directory: This contains the core functionality of the keyboard. Here, you'll find the logic for various key actions, like what happens when the Enter key is pressed or how different keys respond to user interactions. This directory is organized by language, with each language having its own set of actions defined.
- MyKeyboard.kt (in the Helpers Directory): This file serves as a helper that supports the main keyboard functionalities. It acts as a bridge, connecting the service logic with the UI elements.
- MyKeyboardView.kt (in the Views Directory): This file is responsible for the keyboard's visual design. It defines how the keyboard appears to the user and handles the layout of UI elements.
You’ll also find that we can modify some UI elements directly from the Services Directory. For example, when a specific action occurs on the keyboard, we might want to update the UI accordingly.

Now, regarding the specific issue you’re working on, I recommend exploring the switchToToolbar function within the individual language services. Currently, this function changes the color of the top divider; you could also try adjusting the command bar color. In the individual keyboard IME, you’ll find how the colors are set for the translate and other buttons.

If anything I’ve mentioned isn’t clear, please don’t hesitate to ask. I’m here to help!

**Comment by angrezichatterbox** [comment]
Hey @indra057, just checking in to see if you’re still having trouble solving this issue. If you are, please don’t hesitate to ask us; we’re more than happy to help!

**Comment by Akshaykomar890** [comment]
@andrewtavis @angrezichatterbox Can I work on this ?

**Comment by andrewtavis** [comment]
Sure thing, @Akshaykomar890 :) Feel free to send along a PR, and let us know if you have any questions! 

@indra057, you're of course welcome to still contribute here!

**Comment by Akshaykomar890** [comment]
@andrewtavis I can't find this application on play store to check the issue ,so should I first run locally this project in android emulator and test the issue ?

**Comment by Akshaykomar890** [comment]
@andrewtavis @angrezichatterbox I'm encountering the following error in  app, and it prevents the app from launching—it crashes immediately:


FATAL EXCEPTION: main (Ask Gemini)
                                                                                                    Process: be.scri.debug, PID: 13575
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{be.scri.debug/be.scri.activities.MainActivity}: java.lang.UnsupportedOperationException: Can't convert value at index 1 to color: type=0x1
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3516)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3676)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2116)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:236)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7904)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
                                                                                                    Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 1 to color: type=0x1
                                                                                                    	at android.content.res.TypedArray.getColor(TypedArray.java:535)
                                                                                                    	at android.app.Activity.onApplyThemeResource(Activity.java:5189)
                                                                                                    	at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:216)
                                                                                                    	at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:147)
                                                                                                    	at android.app.Activity.setTheme(Activity.java:5167)




>It occurs during the app launch
>Could you assist in identifying the root cause?

**Comment by andrewtavis** [comment]
CC @angrezichatterbox, could you take a look at the above :)

And yes, @Akshaykomar890, the app isn't released, so you'd need to run it locally and test it against the current main branch :)

**Comment by andrewtavis** [comment]
@Akshaykomar890, try switching the color mode of your emulator. We did have an issue with this before in https://github.com/scribe-org/Scribe-Android/issues/155, so maybe we're seeing a version of it again?

**Comment by andrewtavis** [comment]
Fix for that was https://github.com/scribe-org/Scribe-Android/pull/157, so maybe there's a hint for fixing it and then we can commence with this issue? Thanks for communicating your issues!

**Comment by angrezichatterbox** [comment]
Were you able to fix the issue @Akshaykomar890 ?

**Comment by Akshaykomar890** [comment]
@andrewtavis @angrezichatterbox Should I Run. [08ea993](https://github.com/scribe-org/Scribe-Android/commit/08ea993ade2cd5796165d8e0d5cdfbe7ed9fde9d) this branch on my android studio  as you mentioned above #157

**Comment by Akshaykomar890** [comment]
@andrewtavis I am running Android android ladybug

**Comment by Akshaykomar890** [comment]
@andrewtavis  @angrezichatterbox Apologies for not replying earlier to your valuable suggestion; I’ve been tied up with an assignment and a personal project. Thank you for sharing the steps! I’m following them now and will let you know how it goes. I really appreciate your help and the detailed note you added to the setup guide.

Thanks again😊

**Comment by Akshaykomar890** [comment]
@andrewtavis @angrezichatterbox   I am using a physical device, has @angrezichatterbox suggested I first  invalidated the caches and changed  theme from 
**android:theme="@style/AppTheme.Base">** to   **android:theme="@style/Theme.MaterialComponents.DayNight">** app successfully installed but when i try to open keyboard it doesn't open instead showing below error in logcat 





ATAL EXCEPTION: main (Ask Gemini)
                                                                                                    Process: be.scri.debug, PID: 30770
                                                                                                    java.lang.RuntimeException: Unable to create service be.scri.services.EnglishKeyboardIME: android.view.InflateException: Binary XML file line #6 in be.scri.debug:layout/keyboard_view_keyboard: Binary XML file line #6 in be.scri.debug:layout/keyboard_view_keyboard: Error inflating class androidx.constraintlayout.widget.ConstraintLayout
                                                                                                    	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4279)
                                                                                                    	at android.app.ActivityThread.access$1600(ActivityThread.java:246)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1982)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:236)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7904)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #6 in be.scri.debug:layout/keyboard_view_keyboard: Binary XML file line #6 in be.scri.debug:layout/keyboard_view_keyboard: Error inflating class androidx.constraintlayout.widget.ConstraintLayout
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #6 in be.scri.debug:layout/keyboard_view_keyboard: Error inflating class androidx.constraintlayout.widget.ConstraintLayout
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:856)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:963)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:661)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
                                                                                                    	at be.scri.databinding.KeyboardViewKeyboardBinding.inflate(KeyboardViewKeyboardBinding.java:105)
                                                                                                    	at be.scri.databinding.KeyboardViewKeyboardBinding.inflate(KeyboardViewKeyboardBinding.java:99)
                                                                                                    	at be.scri.services.GeneralKeyboardIME.onCreate(GeneralKeyboardIME.kt:105)
                                                                                                    	at be.scri.services.EnglishKeyboardIME.onCreate(EnglishKeyboardIME.kt:137)
                                                                                                    	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4267)
                                                                                                    	at android.app.ActivityThread.access$1600(ActivityThread.java:246)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1982)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:236)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7904)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
                                                                                                    Caused by: android.content.res.Resources$NotFoundException: Drawable be.scri.debug:color/you_keyboard_background_color with resource ID #0x7f0604d9
                                                                                                    Caused by: android.content.res.Resources$NotFoundException: Resource "be.scri.debug:color/you_keyboard_background_color" (7f0604d9) is not a Drawable (color or path): TypedValue{t=0x1/d=0x7f0604d9 a=-1 r=0x7f0604d9}
                                                                                                    	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:848)
                                                                                                    	at android.content.res.ResourcesImpl.originalLoadDrawable(ResourcesImpl.java:693)
                                                                                                    	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:600)
                                                                                                    	at android.content.res.MiuiResourcesImpl.loadDrawable(MiuiResourcesImpl.java:307)
                                                                                                    	at android.content.res.Resources.loadDrawable(Resources.java:1010)
                                                                                                    	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1008)
                                                                                                    	at android.content.res.TypedArray.getDrawable(TypedArray.java:983)
                                                                                                    	at android.view.View.<init>(View.java:5689)
                                                                                                    	at android.view.ViewGroup.<init>(ViewGroup.java:699)
                                                                                                    	at android.view.ViewGroup.<init>(ViewGroup.java:695)
                                                                                                    	at android.view.ViewGroup.<init>(ViewGroup.java:691)
2025-01-24 19:25:03.786 30770-30770 AndroidRuntime          be.scri.debug                        E  	at androidx.constraintlayout.widget.ConstraintLayout.<init>(ConstraintLayout.java:594) (Ask Gemini)
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:856)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:963)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:661)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
                                                                                                    	at be.scri.databinding.KeyboardViewKeyboardBinding.inflate(KeyboardViewKeyboardBinding.java:105)
                                                                                                    	at be.scri.databinding.KeyboardViewKeyboardBinding.inflate(KeyboardViewKeyboardBinding.java:99)
                                                                                                    	at be.scri.services.GeneralKeyboardIME.onCreate(GeneralKeyboardIME.kt:105)
                                                                                                    	at be.scri.services.EnglishKeyboardIME.onCreate(EnglishKeyboardIME.kt:137)
                                                                                                    	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4267)
                                                                                                    	at android.app.ActivityThread.access$1600(ActivityThread.java:246)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1982)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:236)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7904)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by angrezichatterbox** [comment]
Could you try changing in the Main Activity ? Changing in theme overall would cause errors as the keyboard are not using colors from Material Theme ?

**Comment by angrezichatterbox** [comment]
I think the issue you are facing is linked with #174

**Comment by janiceferns02** [comment]
Hello, can I work on this issue?

**Comment by angrezichatterbox** [comment]
@Akshaykomar890 you are currently working on this issue right ?

**Comment by Akshaykomar890** [comment]
@angrezichatterbox I don't have a device higher that api 35 or equal so I am not working on this issue.
Thank you

**Comment by angrezichatterbox** [comment]
Devices with API 31 and above are fine for the app currently

**Comment by angrezichatterbox** [comment]
> [@angrezichatterbox](https://github.com/angrezichatterbox) My physical device's API is 30 (Android 11).

Would you be interested in checking the issue using a simulator ? or else I could get this assigned to @janiceferns02 .

**Comment by Akshaykomar890** [comment]
Yes @angrezichatterbox you can assign to @janiceferns02

**Comment by angrezichatterbox** [comment]
@janiceferns02 Feel free to work on this issue. @Akshaykomar890 I would check for possible fixes on the API 30 issue and get back to you on the other issue.

**Comment by janiceferns02** [comment]
Thank you! I'll start working on the issue and ask here if I need any help.

**Comment by andrewtavis** [comment]
Quick check in here, @janiceferns02 👋 Please let us know if there's anything we can do to support you on this issue 😊 Hope that all's well with you!

**Comment by Akshaykomar890** [comment]
@@andrewtavi @angrezichatterbox  Can you reassign this issue to me I now as device of api above 32 .

**Comment by janiceferns02** [comment]
@andrewtavis Hi, thanks for checking in! Apologies for the delay - I've been caught up with other commitments, but I’m planning to make progress on this soon.

**Comment by andrewtavis** [comment]
Sounds great, @janiceferns02 :) Looking forward to collaborating with you on this 😊

**Comment by janiceferns02** [comment]
@andrewtavis I noticed that the Scribe key background color changes based on the device’s dark or light mode, while the scribe key icon color changes based on the Scribe mode.

Scribe dark mode && device dark mode - scribe key background colour (dark scribe blue) and scribe key icon colour (white)

Scribe dark mode && device light mode - scribe key background colour (light scribe blue) and scribe key icon colour (white)

Scribe light mode && device light mode - scribe key background colour (light scribe blue) and scribe key icon colour (light key text colour  - black shade)

Scribe light mode && device dark mode - scribe key background colour (dark scribe blue) and scribe key icon colour (light key text colour - black shade)

The background colour also depend on the Scribe mode instead of the device mode?

what is the expected behaviour?

**Comment by andrewtavis** [comment]
Thanks for checking this and for the detailed presentation of your findings, @janiceferns02! The expected behavior is that the color of the key should be only changed based on the device color mode. So in dark mode is should always be Scribe dark blue and in light mode it should always be Scribe light blue. 

Do you want to send a PR along to fix this? 😊

**Comment by andrewtavis** [comment]
Note that this is related to #316. Do you want to work on that issue, @janiceferns02? :)

**Comment by janiceferns02** [comment]
@andrewtavis Thanks for the clarification! The background color is working as expected now (only changed based on the device color mode). So I'll update the icon colors accordingly—white for the dark scribe blue background and the black shade for the light scribe blue background (in my next PR).

**Comment by janiceferns02** [comment]
@andrewtavis Thanks for the clarification! The background color is working as expected now (only changed based on the device color mode). So I'll update the icon colors accordingly—white for the dark scribe blue background and the black shade for the light scribe blue background in my next PR.

**Comment by andrewtavis** [comment]
Closed by #334 🚀 Amazing work, @janiceferns02! Please let us know if there's another issue that's of interest for you :)
