### ISSUE TITLE
app crashing at startup on api 30

### ISSUE THREAD

**Issue by MostafaMohamed2002** [scribe-org/Scribe-Android#174]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

when trying to launch the app on api 30 it crashes at startup 
```17:10:07.321  E  FATAL EXCEPTION: main
                 Process: be.scri.debug, PID: 11099
                 java.lang.RuntimeException: Unable to start activity ComponentInfo{be.scri.debug/be.scri.activities.SplashActivity}: java.lang.UnsupportedOperationException: Can't convert value at index 1 to color: type=0x1
                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
                 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
                 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loop(Looper.java:223)
                 	at android.app.ActivityThread.main(ActivityThread.java:7656)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
                 Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 1 to color: type=0x1
                 	at android.content.res.TypedArray.getColor(TypedArray.java:533)
                 	at android.app.Activity.onApplyThemeResource(Activity.java:5104)
                 	at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:216)
                 	at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:147)
                 	at android.app.Activity.setTheme(Activity.java:5082)
                 	at androidx.appcompat.app.AppCompatActivity.setTheme(AppCompatActivity.java:146)
                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3415)
                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
                 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
                 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
                 	at android.os.Handler.dispatchMessage(Handler.java:106) 
                 	at android.os.Looper.loop(Looper.java:223) 
                 	at android.app.ActivityThread.main(ActivityThread.java:7656) 
                 	at java.lang.reflect.Method.invoke(Native Method) 
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

### Device type

Pixel 9 pro api 30

### Versions

latest

**Comment by angrezichatterbox** [comment]
One of the reasons this  is happening is  because the App uses features only available for API 33 and above.  We would have to give else conditions for Versions other TIRAMISU in the program for such features.

**Comment by angrezichatterbox** [comment]
@MostafaMohamed2002 , would you like to work on this after the current PR, or should I try fixing the bug? :)

**Comment by andrewtavis** [comment]
Let us know if any support is needed, @MostafaMohamed2002 :)

**Comment by MahmoudMabrok** [comment]
Hello @MostafaMohamed2002  did you reach a solution and PR is ready? :)

**Comment by MostafaMohamed2002** [comment]
> Hello @MostafaMohamed2002 did you reach a solution and PR is ready? :)

No , if you want to contribute go on

**Comment by MahmoudMabrok** [comment]
@angrezichatterbox I think you can start checking issue when it is possible to you.

**Comment by andrewtavis** [comment]
Thanks for the discussion here, both of you! Please let us know if we can help somehow, @MahmoudMabrok :)

**Comment by angrezichatterbox** [comment]
Hey @MahmoudMabrok , I hope you're doing well. Just checking in to see if you are still working on the issue. Happy to help in case you're facing any issues.

**Comment by MahmoudMabrok** [comment]
@angrezichatterbox  I did not able to check it. if anyone can , please can he go.

**Comment by Akshaykomar890** [comment]
@angrezichatterbox Can I give a try ?

**Comment by Akshaykomar890** [comment]
@angrezichatterbox Sir, I checked my device's API, and it's 30. This is causing the error, but I can't come up with an idea on how to fix it. Can you suggest a way to resolve it ?

**Comment by angrezichatterbox** [comment]
> [@angrezichatterbox](https://github.com/angrezichatterbox) Sir, I checked my device's API, and it's 30. This is causing the error, but I can't come up with an idea on how to fix it. Can you suggest a way to resolve it ?

It would look into it and get back to you :)

**Comment by andrewtavis** [comment]
@MahmoudMabrok, given that others are having issues working with lower APIs, would you be able to give some suggestions here or potentially open a PR if the change is not too involved? :) Any help would be appreciated! 😊

**Comment by linreal** [comment]
@andrewtavis I'll take it, if you don't mind.

**Comment by andrewtavis** [comment]
Assigned, @linreal! And seeing the PR as well 😊 Totally amazing and looking forward to the review! :)

**Comment by andrewtavis** [comment]
Closed by #402 🚀 Amazing to have this finalized! Thanks for the quick work, @linreal 😊

@angrezichatterbox and all: Do we need to factor in API <31 into testing in the future, or was this kind of a one off for this particular issue? What are the normal practices for testing across multiple APIs?
