### ISSUE TITLE
Crash when starting ContributorsActivity

### ISSUE THREAD

**Issue by sunyiming** [scribe-org/Scribe-Android#29]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

When clicking Contributors button on AboutActivity, the app crashed with this following error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.scribe.debug, PID: 3658
    android.content.ActivityNotFoundException: Unable to find explicit activity class {org.scribe.debug/org.scribe.commons.activities.ContributorsActivity}; have you declared this activity in your AndroidManifest.xml?
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2256)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1914)
        at android.app.Activity.startActivityForResult(Activity.java:5326)
        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
        at android.app.Activity.startActivityForResult(Activity.java:5284)
        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:583)
        at android.app.Activity.startActivity(Activity.java:5670)
        at android.app.Activity.startActivity(Activity.java:5623)
        at org.scribe.commons.activities.AboutActivity.setupContributors$lambda-10(AboutActivity.kt:202)
        at org.scribe.commons.activities.AboutActivity.$r8$lambda$sGzhmgoYzkb0ISNY_Q2TUw7oAWQ(Unknown Source:0)
        at org.scribe.commons.activities.AboutActivity$$ExternalSyntheticLambda6.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7520)
        at android.view.View.performClickInternal(View.java:7489)
        at android.view.View.access$3600(View.java:826)
        at android.view.View$PerformClick.run(View.java:28555)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8030)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

### Device type

iPhone

**Comment by andrewtavis** [comment]
Hi @sunyiming, thanks for this! That's a feature that's in from the app this is based on, but we'll definitely have a version in the finished app. I'm about to step out, but will check #30 and merge it later.

Thanks for your efforts!

Am noticing that I need to update the [template for bug reports](https://github.com/scribe-org/Scribe-Android/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml) as well. Sorry that there's still some stuff from iOS in there :)
